
DEBUG = True
SECRET_KEY = 'no'

SITE_NAME = 'DataHub'

BROKER_TRANSPORT = "sqlakombu.transport.Transport"
CELERY_BACKEND = "database" 

SQLALCHEMY_DATABASE_URI = 'sqlite:///datahub.db'
BROKER_HOST = SQLALCHEMY_DATABASE_URI
CELERY_RESULT_DBURI = SQLALCHEMY_DATABASE_URI
